export var state = {
  pacMan: {
    row: 11,
    col: 9,
    direction: null,
    moveTimer: 0,
    moveDelay: 150,
  },

  ghosts: [
    {
      row: 9,
      col: 9,
      startRow: 9,
      startCol: 9,
      direction: null,
      color: "pink",
      moveTimer: 0,
      moveDelay: 150,
      startupTimer: 0,
      startupDelay: 3000,
      hasLeftHouse: false,
      size: 1.1,
    },
    {
      row: 9,
      col: 8,
      startRow: 9,
      startCol: 8,
      direction: null,
      color: "cyan",
      moveTimer: 0,
      moveDelay: 170,
      startupTimer: 0,
      startupDelay: 1800,
      hasLeftHouse: false,
      size: 1.1,
    },
    {
      row: 9,
      col: 10,
      startRow: 9,
      startCol: 10,
      direction: null,
      color: "orange",
      moveTimer: 0,
      moveDelay: 190,
      startupTimer: 0,
      startupDelay: 2400,
      hasLeftHouse: false,
      size: 1.1,
    },
  ],

  score: 0,
  lives: 3,
  hitDelay: 0,
  lastTime: 0,
  deltaTime: 0,
  timeRemaining: 120,
  status: "start",
};
